collections_dir: collections

collections:
  connectors:
    output: true
  protocols:
    output: true

remote_theme: pmarsceill/just-the-docs

defaults:
  - scope:
      path: "/collections/_connectors/*"
    values:
      layout: default
      parent: Connectors
      width: TODO
      height: TODO
      pins: TODO
  - scope:
      path: "/collections/_protocols/*"
    values:
      layout: default
      parent: Protocols
      connector: TODO
      voltage: TODO

just_the_docs:
  collections:
    connectors:
      name: Connectors
    protocols:
      name: Protocols
