collections_dir: collections

collections:
  connectors:
    output: true
  protocols:
    output: true

remote_theme: pmarsceill/just-the-docs

defaults:
  - scope:
      path: ""
    values:
      layout: default
